on:
  push:
    branches:
      - feature/feature1
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
  workflow_dispatch:


jobs:

  docker_build:
    name: Running steps
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker image
      run: docker-compose -f node-docker-app/docker-compose.yml build

    - name: Run Docker container
      run: docker-compose -f node-docker-app/docker-compose.yml up -d

    - name: Show running containers
      run: docker ps

    - name: Stop Docker container
      run: docker stop assignment1_container
